module.exports = [
	['bookNr', '1'],
	['name', '-'],
	['dies', '0'],
	['sex', 'unknown'],
	['age', '30'],
	['isHighBorn', '0'],
	['isWarg', '0'],
	['isMagicUser', '0'],
	['isBastard', '0'],
	['isPOV', '0'],
	['prevChapterAmount', '0'],
	['hasValyrianSteel', '0'],
	['height', '5.5'],
	['hairColor', 'unknown'],
	['eyeColor', 'unknown'],
	['houseAllegiance', 'none'],
	['organization', 'none'],
	['location', 'unknown'],
	['title', 'none'],
];
